:imagesdir: Images
:toc:
:toc-title: Оглавление

[.text-center]
МИНИСТЕРСТВО НАУКИ И ВЫСШЕГО ОБРАЗОВАНИЯ РОССИЙСКОЙ ФЕДЕРАЦИИ +
Федеральное государственное автономное образовательное учреждение высшего образования +
«Южно-Уральский государственный университет» +
(национальный исследовательский университет) +
Высшая школа электроники и компьютерных наук +
Кафедра «Информационно-измерительная техника»

[.text-center]

Отчет по лабораторной работе №11

[.text-right]
Выполнил: +
студент группы КЭ-415 +
Леонов В.А. +
Платонов Д.В.

:toc:
:toc-title: ОГЛАВЛЕНИЕ:

== Лабораторная работа №11
=== Задание
--
Написать программу, которая позволяет моргать светодиодами, с использованием операционных систем реального времени.
--
=== 1. Операционные системы реального времени (OCPB(RTOS))
Данные системы предназначены для обеспечения интерфейса к ресурсам критических по времени систем реального времени.
Оснвной задачей в таких ситемах является своевременность (timeliness) выполнения обработки данных.
Задачей OCPB является обеспечение реакции на определенное действие за отведенный квант времени.
Для разных задач такой квант может иметь разное значение, например, для обработки. Приблизительное время реакции в зависимости от области применения OCPB может быть следующее:
математическое моделирование - несколько микросекунд;
радиолокация - несколько милисекунд;
складской учет - несколько секунд;
управление производством - несколько минут.
